package main.GUI;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import main.Game.Game;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

/**
 *
 * @author ryanj
 */
public class NewJFrame extends JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        button5 = new Button();
        button7 = new Button();
        button12 = new Button();
        button14 = new Button();
        button16 = new Button();
        button17 = new Button();
        button18 = new Button();
        button19 = new Button();
        button20 = new Button();
        button21 = new Button();
        button22 = new Button();
        button23 = new Button();
        button24 = new Button();
        button25 = new Button();
        button26 = new Button();
        button27 = new Button();
        button28 = new Button();
        button29 = new Button();
        button30 = new Button();
        button31 = new Button();
        button32 = new Button();

        button5.setLabel("button1");

        button7.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
         
        // Set the background color to a wood color
        getContentPane().setBackground(new Color(156, 93, 82)); // A medium wood color approximation

        // Setting buttons color to grey
        Color greyColor = new Color(192, 192, 192); // Standard grey color
        button12.setBackground(greyColor);
        button14.setBackground(greyColor);
        button16.setBackground(greyColor);
        button17.setBackground(greyColor);
        button18.setBackground(greyColor);
        button19.setBackground(greyColor);
        button20.setBackground(greyColor);
        button21.setBackground(greyColor);
        button22.setBackground(greyColor);
        button23.setBackground(greyColor);
        button24.setBackground(greyColor);
        button25.setBackground(greyColor);
        button26.setBackground(greyColor);
        button27.setBackground(greyColor);
        button28.setBackground(greyColor);
        button29.setBackground(greyColor);
        button30.setBackground(greyColor);
        button31.setBackground(greyColor);
        button32.setBackground(greyColor);

        button12.setLabel("button1");
        button12.addActionListener(this::button12ActionPerformed);

        button14.setLabel("button1");
        button14.addActionListener(this::button14ActionPerformed);

        button16.setLabel("button1");
        button16.addActionListener(this::button16ActionPerformed);

        button17.setLabel("button1");
        button17.addActionListener(this::button17ActionPerformed);

        button18.setLabel("button1");
        button18.addActionListener(this::button18ActionPerformed);

        button19.setLabel("button1");
        button19.addActionListener(this::button19ActionPerformed);

        button20.setLabel("button1");
        button20.addActionListener(this::button20ActionPerformed);

        button21.setLabel("button1");
        button21.addActionListener(this::button21ActionPerformed);

        button22.setLabel("button1");
        button22.addActionListener(this::button22ActionPerformed);

        button23.setLabel("button1");
        button23.addActionListener(this::button23ActionPerformed);

        button24.setLabel("button1");
        button24.addActionListener(this::button24ActionPerformed);

        button25.setLabel("button1");
        button25.addActionListener(this::button25ActionPerformed);

        button26.setLabel("button1");
        button26.addActionListener(this::button26ActionPerformed);

        button27.setLabel("button1");
        button27.addActionListener(this::button27ActionPerformed);

        button28.setLabel("button1");
        button28.addActionListener(this::button28ActionPerformed);

        button29.setLabel("button1");
        button29.addActionListener(this::button29ActionPerformed);

        button30.setLabel("button1");
        button30.addActionListener(this::button30ActionPerformed);

        button31.setLabel("button1");
        button31.addActionListener(this::button31ActionPerformed);

        button32.setLabel("button1");
        button32.addActionListener(this::button32ActionPerformed);
        button5.setLabel("button5");
        button7.setLabel("button7");
        button12.setLabel("button12");
        button14.setLabel("button14");
        button16.setLabel("button16");
        button17.setLabel("button17");
        button18.setLabel("button18");
        button19.setLabel("button19");
        button20.setLabel("button20");
        button21.setLabel("button21");
        button22.setLabel("button22");
        button23.setLabel("button23");
        button24.setLabel("button24");
        button25.setLabel("button25");
        button26.setLabel("button26");
        button27.setLabel("button27");
        button28.setLabel("button28");
        button29.setLabel("button29");
        button30.setLabel("button30");
        button31.setLabel("button31");
        button32.setLabel("button32");
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button22, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button19, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button30, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button25, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(button27, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button28, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button29, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(button32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(button26, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button21, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button25, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button24, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button12, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button14, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button19, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button30, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button22, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button17, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(button23, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(button27, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button28, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button29, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>                        

    private void button12ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button14ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button16ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button17ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button18ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button19ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button20ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button21ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button22ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button23ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button24ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button25ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button26ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button27ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button28ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button29ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button30ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button31ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void button32ActionPerformed(ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
        Game.CreateGame();
    }

    // Variables declaration - do not modify                     
    private Button button12;
    private Button button14;
    private Button button16;
    private Button button17;
    private Button button18;
    private Button button19;
    private Button button20;
    private Button button21;
    private Button button22;
    private Button button23;
    private Button button24;
    private Button button25;
    private Button button26;
    private Button button27;
    private Button button28;
    private Button button29;
    private Button button30;
    private Button button31;
    private Button button32;
    private Button button5;
    private Button button7;
    // End of variables declaration                   
}
